using System.Collections.Immutable;

namespace FactoryCompiler.Model.DefaultGameDataFiles;

internal class ConstructorData : DefaultGameDataBase, IFactoryData
{
    public static Factory Constructor { get; } = new Factory("Constructor");

    public Factory Factory => Constructor;

    public Recipe[] Recipes { get; } =
    {
        new Recipe("Alien DNA Capsule", new Duration(6),
            Constructor,
            Item.List(new Item("Alien Protein").Volume(1)),
            Item.List(new Item("Alien DNA Capsule").Volume(1))),
        new Recipe("Aluminum Casing", new Duration(2),
            Constructor,
            Item.List(new Item("Aluminum Ingot").Volume(3)),
            Item.List(new Item("Aluminum Casing").Volume(2))),

        new Recipe("Biomass (Alien Protein)", new Duration(4),
            Constructor,
            Item.List(new Item("Alien Protein").Volume(1)),
            Item.List(new Item("Biomass").Volume(100))),
        new Recipe("Biomass (Leaves)", new Duration(5),
            Constructor,
            Item.List(new Item("Leaves").Volume(10)),
            Item.List(new Item("Biomass").Volume(5))),
        new Recipe("Biomass (Mycelia)", new Duration(4),
            Constructor,
            Item.List(new Item("Mycelia").Volume(10)),
            Item.List(new Item("Biomass").Volume(10))),
        new Recipe("Biomass (Wood)", new Duration(4),
            Constructor,
            Item.List(new Item("Wood").Volume(4)),
            Item.List(new Item("Biomass").Volume(20))),

        new Recipe("Cable", new Duration(2),
            Constructor,
            Item.List(new Item("Wire").Volume(2)),
            Item.List(new Item("Cable").Volume(1))),
        new Recipe("Color Cartridge", new Duration(6),
            Constructor,
            Item.List(new Item("Flower Petals").Volume(5)),
            Item.List(new Item("Color Cartridge").Volume(10))),
        new Recipe("Concrete", new Duration(4),
            Constructor,
            Item.List(new Item("Limestone").Volume(3)),
            Item.List(new Item("Concrete").Volume(1))),
        new Recipe("Copper Powder", new Duration(6),
            Constructor,
            Item.List(new Item("Copper Ingot").Volume(30)),
            Item.List(new Item("Copper Powder").Volume(5))),
        new Recipe("Copper Sheet", new Duration(6),
            Constructor,
            Item.List(new Item("Copper Ingot").Volume(2)),
            Item.List(new Item("Copper Sheet").Volume(1))),

        new Recipe("Empty Canister", new Duration(4),
            Constructor,
            Item.List(new Item("Plastic").Volume(2)),
            Item.List(new Item("Empty Canister").Volume(4))),
        new Recipe("Empty Fluid Tank", new Duration(1),
            Constructor,
            Item.List(new Item("Aluminum Ingot").Volume(1)),
            Item.List(new Item("Empty Fluid Tank").Volume(1))),

        new Recipe("Hatcher Protein", new Duration(3),
            Constructor,
            Item.List(new Item("Hatcher Remains").Volume(1)),
            Item.List(new Item("Alien Protein").Volume(1))),
        new Recipe("Hog Protein", new Duration(3),
            Constructor,
            Item.List(new Item("Hog Remains").Volume(1)),
            Item.List(new Item("Alien Protein").Volume(1))),

        new Recipe("Iron Plate", new Duration(6),
            Constructor,
            Item.List(new Item("Iron Ingot").Volume(3)),
            Item.List(new Item("Iron Plate").Volume(2))),
        new Recipe("Iron Rebar", new Duration(4),
            Constructor,
            Item.List(new Item("Iron Rod").Volume(1)),
            Item.List(new Item("Iron Rebar").Volume(1))),
        new Recipe("Iron Rod", new Duration(4),
            Constructor,
            Item.List(new Item("Iron Ingot").Volume(1)),
            Item.List(new Item("Iron Rod").Volume(1))),

        new Recipe("Power Shard (1)", new Duration(8),
            Constructor,
            Item.List(new Item("Blue Power Slug").Volume(1)),
            Item.List(new Item("Power Shard").Volume(1))),
        new Recipe("Power Shard (2)", new Duration(12),
            Constructor,
            Item.List(new Item("Yellow Power Slug").Volume(1)),
            Item.List(new Item("Power Shard").Volume(2))),
        new Recipe("Power Shard (5)", new Duration(24),
            Constructor,
            Item.List(new Item("Purple Power Slug").Volume(1)),
            Item.List(new Item("Power Shard").Volume(5))),

        new Recipe("Quartz Crystal", new Duration(8),
            Constructor,
            Item.List(new Item("Raw Quartz").Volume(5)),
            Item.List(new Item("Quartz Crystal").Volume(3))),
        new Recipe("Quickwire", new Duration(5),
            Constructor,
            Item.List(new Item("Caterium Ingot").Volume(1)),
            Item.List(new Item("Quickwire").Volume(5))),

        new Recipe("Screw", new Duration(6),
            Constructor,
            Item.List(new Item("Iron Rod").Volume(1)),
            Item.List(new Item("Screw").Volume(4))),
        new Recipe("Silica", new Duration(8),
            Constructor,
            Item.List(new Item("Raw Quartz").Volume(3)),
            Item.List(new Item("Silica").Volume(5))),
        new Recipe("Solid Biofuel", new Duration(4),
            Constructor,
            Item.List(new Item("Biomass").Volume(8)),
            Item.List(new Item("Solid Biofuel").Volume(4))),
        new Recipe("Spitter Protein", new Duration(3),
            Constructor,
            Item.List(new Item("Plasma Spitter Remains").Volume(1)),
            Item.List(new Item("Alien Protein").Volume(1))),
        new Recipe("Steel Beam", new Duration(4),
            Constructor,
            Item.List(new Item("Steel Ingot").Volume(4)),
            Item.List(new Item("Steel Beam").Volume(1))),
        new Recipe("Steel Pipe", new Duration(6),
            Constructor,
            Item.List(new Item("Steel Ingot").Volume(3)),
            Item.List(new Item("Steel Pipe").Volume(2))),
        new Recipe("Stinger Protein", new Duration(3),
            Constructor,
            Item.List(new Item("Stinger Remains").Volume(1)),
            Item.List(new Item("Alien Protein").Volume(1))),

        new Recipe("Wire", new Duration(4),
            Constructor,
            Item.List(new Item("Copper Ingot").Volume(1)),
            Item.List(new Item("Wire").Volume(2))),
    };

    public Recipe[] AlternateRecipes { get; } =
    {
        new Recipe("Biocoal", new Duration(12),
            Constructor,
            Item.List(new Item("Biomass").Volume(5)),
            Item.List(new Item("Coal").Volume(6)),
            RecipeFlags.Alternate),

        new Recipe("Cast Screw", new Duration(24),
            Constructor,
            Item.List(new Item("Iron Ingot").Volume(5)),
            Item.List(new Item("Screw").Volume(20)),
            RecipeFlags.Alternate),
        new Recipe("Caterium Wire", new Duration(4),
            Constructor,
            Item.List(new Item("Caterium Ingot").Volume(1)),
            Item.List(new Item("Wire").Volume(8)),
            RecipeFlags.Alternate),
        new Recipe("Charcoal", new Duration(4),
            Constructor,
            Item.List(new Item("Wood").Volume(1)),
            Item.List(new Item("Coal").Volume(10)),
            RecipeFlags.Alternate),

        new Recipe("Iron Wire", new Duration(24),
            Constructor,
            Item.List(new Item("Iron Ingot").Volume(5)),
            Item.List(new Item("Wire").Volume(9)),
            RecipeFlags.Alternate),

        new Recipe("Steel Canister", new Duration(3),
            Constructor,
            Item.List(new Item("Steel Ingot").Volume(3)),
            Item.List(new Item("Empty Canister").Volume(2)),
            RecipeFlags.Alternate),
        new Recipe("Steel Rod", new Duration(5),
            Constructor,
            Item.List(new Item("Steel Ingot").Volume(1)),
            Item.List(new Item("Iron Rod").Volume(4)),
            RecipeFlags.Alternate),
        new Recipe("Steel Screw", new Duration(12),
            Constructor,
            Item.List(new Item("Steel Beam").Volume(1)),
            Item.List(new Item("Screw").Volume(52)),
            RecipeFlags.Alternate),
    };

    public Recipe[] ProjectAssemblyRecipes { get; } =
    {
    };
}
